services:
  cuppie_forms_api:
    image: cuppie_forms_api
    build:
      context: .
      dockerfile: cuppie_forms_api/Dockerfile
    container_name: api
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=cuppie_database;Username=cuppie;Password=cupcup
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Password=cupcupcup
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/SslSertificate.pfx
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ./certs:/https  # Проброс директории с сертификатом

  cuppie_forms_frontend:
    image: cuppie_forms_frontend
    build:
      context: .
      dockerfile: cuppie_forms/Dockerfile
    ports:
      - "3000:80"
    container_name: front
    depends_on:
      - cuppie_forms_api
    volumes:
      - ./cuppie_forms/nginx.conf:/etc/nginx/conf.d/default.conf

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: cuppie_database
      POSTGRES_USER: cuppie
      POSTGRES_PASSWORD: cupcup
    ports:
      - "5432:5432"
    container_name: db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: