version: '3.8'

services:
  app:
    image: cuppieforms
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: my_app
    restart: always
    ports:
      - "5000:5000"  
      - "5001:5001"
    volumes:
      - ./keys:/root/.aspnet/DataProtection-Keys
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000  
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=mydb;Username=postgres;Password=secret
    depends_on:
      - db  # Запускать `db` перед `app`

  db:
    image: postgres:16  # Загружаем PostgreSQL 16
    container_name: my_postgres
    restart: always
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./pgdata:/var/lib/postgresql/data  # Сохранение данных
    ports:
      - "5432:5432"
