services:
  app:
    image: cuppieforms
    container_name: my_app
    restart: always
    ports:
      - "5000:5000"  
      - "5001:5001"

    environment:
      - ASPNETCORE_ENVIRONMENT=Production  
      - ASPNETCORE_URLS=http://+:5000 
