services:
  app:
    image: cuppieforms
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: my_app
    restart: always
    ports:
      - "5000:5000"  
      - "5001:5001"

    volumes:
      - ./keys:/root/.aspnet/DataProtection-Keys


    environment:
      - ASPNETCORE_ENVIRONMENT=Production  
      - ASPNETCORE_URLS=http://+:5000 
