# This is a generated file. Not intended for manual editing.
services:
  cuppie_forms_api:
    build:
      context: "C:\\Users\\Cuppie\\RiderProjects\\cuppie_forms_api"
      dockerfile: "Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/Cuppie.Api.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "cuppie_forms_api:dev"
    ports: []
    volumes:
    - "C:\\Users\\Cuppie\\RiderProjects\\cuppie_forms_api\\src\\Cuppie.Api:/app:rw"
    - "C:\\Users\\Cuppie\\RiderProjects\\cuppie_forms_api:/src:rw"
    - "C:\\Users\\Cuppie\\.nuget\\packages:/root/.nuget/packages"
    working_dir: "/app"
