# This is a generated file. Not intended for manual editing.
services:
  cuppie_forms_backend:
    build:
      context: "C:\\Users\\Cuppie\\RiderProjects\\CuppieForms\\cuppie_forms_backend"
      dockerfile: "Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/Cuppie.Api.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "cuppie_forms_backend:dev"
    ports: []
    volumes:
    - "C:\\Users\\Cuppie\\RiderProjects\\CuppieForms\\cuppie_forms_backend\\src\\\
      Cuppie.Api:/app:rw"
    - "C:\\Users\\Cuppie\\RiderProjects\\CuppieForms\\cuppie_forms_backend:/src:rw"
    - "C:\\Users\\Cuppie\\.nuget\\packages:/root/.nuget/packages"
    working_dir: "/app"
